### PR TITLE
Fix undefined array key warning in TokenAuthenticationService

### PR DESCRIPTION
**Pull request by schliesser**
[WARNING] request="99e57da6573ed" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (BE): PHP Warning: Undefined array key "msblToken" in /var/www/html/app/public/typo3conf/ext/multisite_belogin/Classes/Authentication/TokenAuthenticationService.php line 76

### CODE REVIEW

**Comment by svewap** [comment]
Hi. Thank you for patching. You make a check with isset on $_POST but then you use the $_GET variable?

**Comment by schliesser** [comment]
> Hi. Thank you for patching. You make a check with isset on $_POST but then you use the $_GET variable?

Copy&Pasta error while copying to GitHub 🙈 Fixed it

**Comment by mikestreety** [comment]
Is it possible for this to be merged please? Would be hugely appreciated!

Thanks for the great work with this :)

**Comment by mikestreety** [comment]
To link it, this solves https://github.com/WapplerSystems/t3-multisite_belogin/issues/9

**Pull request merged**
